### ISSUE TITLE
Add dealii-preCICE Laplace problem

### ISSUE THREAD

**Issue by uekerman** [xsdk-project/xsdk-examples#21]
I found out about the xSDK examples today. If there is interest in adding further cases, this one could be a good option:

https://github.com/dealii/code-gallery/tree/master/coupled_laplace_problem

It is a very simple, actually even a bit artificial example how to use deal.II with preCICE. One could configure a PETSc-based RBF mapping in preCICE. And I guess in deal.II, once could probably use another xSDK dependency as a linear solver.

Different to the existing examples would be that one needs to build two executables (we want to couple them via preCICE) and that a preCICE configuration file is required.

Please note that this is not a good candidate for performance testing. It is just the simplest thing one can construct with deal.II and preCICE.

Just putting this out there. I am happy to provide more information and help contributing if this sounds interesting.

@fsimonis @davidscn @kronbichler

**Comment by v-dobrev** [comment]
Hi @uekerman,

I'll try to help you with adding this example.

I'll ask someone to add you to the "xsdk-project" org so that you can create a branch directly in this repository.
