### ISSUE TITLE
New example: PUMI/Omega_h+MFEM

### ISSUE THREAD

**Issue by v-dobrev** [xsdk-project/xsdk-examples#30]
Description: Adaptive mesh refinement for a diffusion problem using MFEM+PUMI

**Comment by cwsmith** [comment]
@v-dobrev Could this pumi-mfem example:
https://github.com/mfem/mfem/blob/d4bc14a48a1781ae4f7a16855f98c491f1e98389/examples/pumi/ex6p.cpp
work for this?

**Comment by v-dobrev** [comment]
I think that is one option. I wanted to discuss this with you. :-)

One constraint is that we want to have an example that does not need a big input file -- it is probably best to include the needed input files in the repo and we don't want to add big files.

**Comment by cwsmith** [comment]
Is ~1MB too large for inputs?

**Comment by v-dobrev** [comment]
I'm not sure, maybe 1MB is okay. I can bring it up at the next meeting to see what others think.

What's probably more important is to make sure we have a test run that does not require a lot of time to run, so it can be used as a CMake test and be run during CI. Maybe runtime of less than 1 min is a reasonable target.

Of course, I think bigger, more interesting problems, can be listed as sample runs in the `README.md` file in the directory where this new example will be.

**Comment by cwsmith** [comment]
@v-dobrev The 10k element mesh is here:

https://github.com/mfem/data/tree/7a8cfaf6f0a616d2cc536674b709ba1c6847b4ae/pumi/parallel/KovaLinear

It should be used with the `.dmg` geometric model here:

https://github.com/mfem/data/blob/7a8cfaf6f0a616d2cc536674b709ba1c6847b4ae/pumi/geom/Kova.dmg

I ran ex6p with the following arguments:

```
data=/path/to/mfem/data/repo/pumi
mpirun -np 2 ./ex6p --mesh $data/parallel/KovaLinear/Kova-linear-10k_2p.smb -p $data/geom/Kova.dmg
```

**Comment by v-dobrev** [comment]
Thank @cwsmith, I added the mesh files in PR #43.
