### ISSUE TITLE
plasma example build error [with xsdk@0.8.0]

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-examples#38]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-examples/files/11355537/spack-build-out.txt)

Ref:
```
balay@xsdk:/data/balay/spack> nice ./bin/spack install  --test=root --fail-fast -j32 xsdk-examples@0.4.0%gcc@9.2.0+cuda cuda_arch=70 ^cuda@11.6.0 ^openmpi ^xsdk@0.8.0+trilinos
```

**Comment by v-dobrev** [comment]
@balay, can you please add to the top post which Spack branch and repo you are using?

(I see `xsdk-examples@0.4.0` so I assume it is not the main Spack repo and branch.)

**Comment by balay** [comment]
I had some local edits for this test. I see you've pushed `packages/xsdk-examples-v0.4.0` branch. So I added a minor change to it
