### ISSUE TITLE
sundials example failure with xsdk@0.8.0

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-examples#39]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-examples/files/11355571/spack-build-out.txt)

Ref:
```
balay@xsdk:/data/balay/spack> nice ./bin/spack install  --test=root --fail-fast -j32 xsdk-examples@0.4.0%gcc@9.2.0+cuda cuda_arch=70 ^cuda@11.6.0 ^openmpi ^xsdk@0.8.0+trilinos

```

**Comment by v-dobrev** [comment]
@balay, can you please add to the top post which Spack branch and repo you are using?

(I see `xsdk-examples@0.4.0` so I assume it is not the main Spack repo and branch.)

**Comment by balay** [comment]
Posted a response at https://github.com/xsdk-project/xsdk-examples/issues/38#issuecomment-1528795387

**Comment by v-dobrev** [comment]
I think this issue was fixed in #42 which is now merged in `master` and also in `testing-v0.4.0`. I think we can close this.

@balay, if you agree, please close this.

**Comment by balos1** [comment]
Is this issue resolved?

**Comment by balay** [comment]
Yes I think this issue is resolved [as the build goes through further]

And perhaps the following change was the fix:


https://github.com/xsdk-project/xsdk-examples/pull/43/commits/d11b946fe19d758ad4e5f33518dd0eb9e63d4479
