### ISSUE TITLE
trilinos example build failure

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-examples#46]
ref: [amrex, mfem, plasma, sundials off]
```
balay@xsdk:/data/balay/spack>nice ./bin/spack install --keep-stage --dont-restage --test=root --fail-fast -j32 xsdk-examples@0.4.0%gcc@9.2.0+cuda cuda_arch=70 ^cuda@11.6.0 ^openmpi ^xsdk@0.8.0+trilinos+cuda cuda
_arch=70 ^dealii~hdf5
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-examples/files/11456270/spack-build-out.txt)

**Comment by v-dobrev** [comment]
### Issue 1
Looking at the log file, one issue I see, is the same Slate issue (ping @mgates3) we saw in #38:
```console
In file included from /data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/openmp.hh:53,
                 from /data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/Memory.hh:21,
                 from /data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/BaseMatrix.hh:10,
                 from /data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/Matrix.hh:9,
                 from /data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/slate.hh:9,
                 from /data/balay/spack/spack-stage/spack-stage-xsdk-examples-0.4.0-gnzp7hwpbqnelam2p34q5hjtmxcaivcn/spack-src/plasma/ex1solve.cpp:12:
/data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/OmpSetMaxActiveLevels.hh: In constructor 'slate::OmpSetMaxActiveLevels::OmpSetMaxActiveLevels(int)':
/data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/OmpSetMaxActiveLevels.hh:38:38: error: 'omp_get_max_active_levels' was not declared in this scope; did you mean 'orig_max_active_levels_'?
   38 |         int curr_max_active_levels = omp_get_max_active_levels();
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      orig_max_active_levels_
/data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/OmpSetMaxActiveLevels.hh:46:13: error: 'omp_set_max_active_levels' was not declared in this scope; did you mean 'orig_max_active_levels_'?
   46 |             omp_set_max_active_levels( min_active_levels );
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             orig_max_active_levels_
/data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/OmpSetMaxActiveLevels.hh: In destructor 'slate::OmpSetMaxActiveLevels::~OmpSetMaxActiveLevels()':
/data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/slate-2022.07.00-e6alify3pwqvhm3ajj5x2d3x5gpwjizw/include/slate/internal/OmpSetMaxActiveLevels.hh:56:13: error: 'omp_set_max_active_levels' was not declared in this scope; did you mean 'orig_max_active_levels_'?
   56 |             omp_set_max_active_levels( orig_max_active_levels_ );
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             orig_max_active_levels_
```
This is fixed by the workaround from #48 that resolves #38, however, it will be best to resolve it in Slate in the future.

### Issue 2
Another issue I see is that Trilinos finds the Kokkos headers from the `kokkos` package instead of the Kokkos headers that come with Trilinos itself. To avoid this issue, I've been disabling the `arborx` variant of `xsdk` -- `arborx` is the package that brings the `kokkos` dependency. Also, we don't have any `arborx` examples in `xsdk-examples`, so it should be fine to disable it for testing `xsdk-examples`, for now.

**Comment by mgates3** [comment]
Issue 1 is that SLATE is compiled _with_ and requires OpenMP, and the application example tries to compile _without_ OpenMP. I don't know how SLATE's CMake could force applications to compile with OpenMP (i.e., adding `-fopenmp` to their CXXFLAGS and LDFLAGS). In our CMake we already have:
```
    target_link_libraries( slate PUBLIC "OpenMP::OpenMP_CXX" )
```
and in `slateConfig.cmake.in` have
```
if (slate_use_openmp)
    find_dependency( OpenMP )
endif()
```
It's highly unlikely that SLATE would remove the OpenMP dependency. (The CMake script technically has an option to turn off OpenMP, but it's untested, obviously breaks, and should thus probably be removed.) We could put in a more obvious failure like:
```
#ifdef _OPENMP
    #include <omp.h>
#else
    #error SLATE requires OpenMP (e.g., -fopenmp in CXXFLAGS and LDFLAGS)
#endif
```

**Comment by v-dobrev** [comment]
@mgates3, thanks for the clarifications!

In the xSDK examples repo, there's a Slate module file: `cmake/FindSlate.cmake` which does not handle the OpenMP dependency. It should be easy to add it though.

Another option is to remove the module file and use the exported Slate CMake file, `slateConfig.cmake`, that you mentioned.

**Comment by mgates3** [comment]
I would use `slateConfig.cmake`. That's the standard way of doing things with CMake, right? @luszczek

**Comment by v-dobrev** [comment]
> I would use `slateConfig.cmake`. That's the standard way of doing things with CMake, right? @luszczek

@luszczek, if you agree, can you please make this change in your PR, #48?

**Comment by luszczek** [comment]
I see quite a few questions here:

1. Do we handle OpenMP as dependency or abandon it? `xsdk-examples` 0.3 were testing for it but not using it.
2. What are the requirements for projects included in `xsdk-examples` regarding their dependencies? It seems we're changing it now from `Find*` to exported targets.
3. How do we handle a problem that appears across different issues? Right now #46 and #48 are duplicates

**Comment by v-dobrev** [comment]
I think it is best to use exported CMake files (like `slateConfig.cmake`) when an xSDK package exports such file. For other packages, we need the `cmake/Find*.cmake` modules. The main reason is that the exported CMake files contain all required dependencies and we do not need to copy, update, and duplicate that in the xSDK examples CMake build system.

**Comment by v-dobrev** [comment]
I think this issue is resolved with the latest test branches, here (https://github.com/xsdk-project/xsdk-examples/tree/testing-v0.4.0) and in Spack (https://github.com/spack/spack/pull/37295).

The only remaining discussion is about potentially using `slateConfig.cmake` instead of the `cmake/FindSlate.cmake` module. We can move the discussion about that to #48 as an alternative solution of #38.
